### PR TITLE
Styling the project page for individual projects + tweaking the styling of project settings container 

### LINKED ISSUE #33: Styling generated project pages
There's no styling on them currently.

NOTE: There are already plans to style the tags (class "project_label")

### PR DESCRIPTION
**Pull request by HlaKarki**
closes #33

### CODE REVIEW

**Comment by trentonyo** [comment]
Center and increase width of elements so that they look "justified"

Flex and justify tag checkboxes

**Comment by HlaKarki** [comment]
> Center and increase width of elements so that they look "justified"
> 
> Flex and justify tag checkboxes

complied with the above reviews

**Comment by HlaKarki** [comment]
closes #45

**Comment by HlaKarki** [comment]
closes #44

**Comment by HlaKarki** [comment]
closes #43 
added href to the thumbnail

**Pull request merged**
