### PR TITLE
Styling the home and editor page v.2.0

### LINKED ISSUE #32: Text editor area should resize
Currently, the textarea grows to behind the next div, and the container does not grow along with it

### PR DESCRIPTION
**Pull request by HlaKarki**
closes #32

### CODE REVIEW

**Comment by HlaKarki** [comment]
closes #32

**Review by trentonyo — APPROVED** [review]
Looks excellent!

**Comment by trentonyo** [comment]
I'm going to implement the "labels checkbox" thing we talked about, @HlaKarki

**Comment by HlaKarki** [comment]
> I'm going to implement the "labels checkbox" thing we talked about, @HlaKarki

Oo sure thing! I forgot about that one yeah.

**Comment by trentonyo** [comment]
Improved functionality of [label checkboxes](https://github.com/trentonyo/riceCAD/pull/35/commits/dac9e955113b639aa41c7cfc53d0b6883c6a318d) so all the UX improvements have been merged into this PR, so...

### Overview
Just added some of the functional improvements planned to the Editor and Projects Pages, closes a few issues

### Changes
- Closes #28 which I called "remix this project" by adding a button on the project page and introducing an additional piece of metadata if a project is based on another.
- Publishing a project now redirects the user to that project's page, this closes #29 
- Added a button to the project page which copies that projects' ID to the user's clipboard (closes #30 )

**Review by trentonyo — APPROVED** [review]
All changes approved

**Pull request merged**
